// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjTl8GjpzmXihoFxxssqZ5QdrAuJ27U4g',
    appId: '1:821383997749:web:66c2240136103c37b4447c',
    messagingSenderId: '821383997749',
    projectId: 'metalhuman-e7997',
    authDomain: 'metalhuman-e7997.firebaseapp.com',
    storageBucket: 'metalhuman-e7997.firebasestorage.app',
    measurementId: 'G-N1F42BJ3SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnyvlWLQMzRV6vMWct0FT_KtU9_8Fc2Gw',
    appId: '1:821383997749:android:bc662eb513264df9b4447c',
    messagingSenderId: '821383997749',
    projectId: 'metalhuman-e7997',
    storageBucket: 'metalhuman-e7997.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu5UASoZYedxoaVVyeVnaAaikJ8qfDduY',
    appId: '1:821383997749:ios:fe13782badd45f00b4447c',
    messagingSenderId: '821383997749',
    projectId: 'metalhuman-e7997',
    storageBucket: 'metalhuman-e7997.firebasestorage.app',
    iosClientId: '821383997749-vdsbvofni2c1eegn1fcgsrofddmc5g6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.metalHuman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu5UASoZYedxoaVVyeVnaAaikJ8qfDduY',
    appId: '1:821383997749:ios:fe13782badd45f00b4447c',
    messagingSenderId: '821383997749',
    projectId: 'metalhuman-e7997',
    storageBucket: 'metalhuman-e7997.firebasestorage.app',
    iosClientId: '821383997749-vdsbvofni2c1eegn1fcgsrofddmc5g6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.metalHuman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjTl8GjpzmXihoFxxssqZ5QdrAuJ27U4g',
    appId: '1:821383997749:web:f5767fbc3910aae5b4447c',
    messagingSenderId: '821383997749',
    projectId: 'metalhuman-e7997',
    authDomain: 'metalhuman-e7997.firebaseapp.com',
    storageBucket: 'metalhuman-e7997.firebasestorage.app',
    measurementId: 'G-5XN2BX38H4',
  );
}
